-- AlterTable
ALTER TABLE "Machine" ADD COLUMN "greased" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Machine" ADD COLUMN "dirt" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Machine" ADD COLUMN "greaseSkipStreak" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Machine" ADD COLUMN "breakdown" TEXT;
